name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: [ '1.22', '1.21' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: go mod tidy
        env:
          LOG_LEVEL: ${{ inputs.logLevel }}

      # Build Watch
      - name: Build watch (main application)
        run: go build -o bin/watch.exe ./cmd/watch
        env:
          LOG_LEVEL: ${{ inputs.logLevel }}

      # Build Installer
      - name: Build installer
        run: go build -o bin/watch.exe ./cmd/install
        env:
          LOG_LEVEL: ${{ inputs.logLevel }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out.exe
          path: bin/out.exe
        env:
          LOG_LEVEL: ${{ inputs.logLevel }}